### PR TITLE
GHA Migration

### PR DESCRIPTION
**Pull request by ggenzone**

### CODE REVIEW

**Comment by ggenzone** [comment]
@akseldavis To migrate to GH Actions and because this repository uses the onetrust branch, I need you to update the 'onetrust' branch in Jekyll with the latest of the main branches.

**Comment by akseldavis** [comment]
@ggenzone Updated. We can also temporarily switch back to `main` if needed.

**Comment by ggenzone** [comment]
> @ggenzone Updated. We can also temporarily switch back to `main` if needed.

It shouldn't be necessary. Seems fine

**Comment by ggenzone** [comment]
I saw it once and I had to force it, I thought that only in the migration if it is done manually could I see that.

What was the PR that generated that?

It's weird that Github sometimes seems to expect a CI that isn't in the files.

**Pull request merged**
